bootstrap:
	bundle install --path="vendor/bundle"
	bundle update
	bundle exec pod keys set "SlackToken" "xoxp-4698769766-4698769768-4898023905-7a1afa"
	bundle exec pod install
	bundle exec pod update

bundle: 
	bundle exec pod install

update:
	bundle install
	bundle update
	bundle exec pod install
	bundle exec pod update
