platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

def pods
  pod 'Moya', '~> 1.1.1'
  pod 'HexColors', '~> 2.2.1'
  pod 'ReactiveViewModel'
end

pods
pod 'SDWebImage', '~> 3.7.2'
pod 'ReachabilitySwift', '~> 1.1'

target 'SlackTeamExplorerTests' do
    pod 'Quick', '~> 0.3.1'
    pod 'Nimble', '~> 1.0.0-final'
end

plugin 'cocoapods-keys', {
	:project => "SlackTeamExplorer",
	:keys => [
	  "SlackToken"
  ]}
